name: test images tag

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # no test is required
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@main

      - name: Prepare the TAG
        id: prepare-the-tag
        run: |
          # strip git ref prefix from version
          TAG=""
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ $VERSION = "main" ]; then
            TAG="latest"
          fi
          echo "TAG=${TAG}"
          echo "TAG=${TAG}" >> $GITHUB_STATE
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
      - name: test TAG
        run: |
          TAG=${{steps.prepare-the-tag.outputs.TAG}}
          echo "TAG=${TAG}"
